google/tie

client/services/code_preprocessors/PythonCodePreprocessorService.js, client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js
So this isn't a fix and doesn't include linear regression, but I figured while I read up on that I can at least delete the line of code that's causing the issue for y'all. (Currently it looks like skulpt supports numpy but it doesn't say anything about scipy, which is where the linear regression model lives, so I may have to do a bit more work with this bit. Will update.)
I've tested and verified that this allows you to at least proceed through the end of question 2, but it won't work for i18n because that requires a constant-time solution, which is something that needs added.
To that end, I think it's likely better to get constant time working so that we can move through the entire flow, or to remove it altogether.
=> Unbreak performance test

client/services/FeedbackGeneratorService.js, client/services/FeedbackGeneratorServiceSpec.js
Note: this also fixes the error @apicardgoog reported where typing "return {}" results in no error and no system feedback.
=> Fix #40: parse all possible JS variables human-readably.

client/components/LearnerViewDirective.js
Enabled context-sensitive indentation.
=> Enable auto indent (#90)

client/components/LearnerViewDirective.js
Resolving #92 
Bug on line 62 - look [here](https://github.com/angular-ui/ui-codemirror#options) for reference
The blank line and space characters just before closing the ui-codemirror tag are preserved, and after undo is used they appear in the code instead of a blank editor.
=> Fixed random text appearing when undo from default code

client/components/LearnerViewDirective.js
The representation turns to a check mark when the question is completed. 
Screenshot:
=> Fix #154: Show check mark instead of number when question is completed.

assets/tests/QuestionSchemaValidationServiceSpec.js
A new key-value pair is added to globalData.questions in each &lt;question>.js file. Thus we can get the list of question IDs from keys of globalData.questions, I guess?
=> get question IDs from keys of question dict.

client/domain/CorrectnessTestObjectFactory.js
Now, learner's code can output list of strings and correctness test will be able to return `True` if any of the allowedOutputs has the same strings (and in same order) as list of strings that learner's code output. 
The approach is to stringify list of strings so that they can be compared.
=> Add feature to correctness test: support comparing list of strings

client/services/code_preprocessors/CodePreprocessorDispatcherServiceSpec.js, client/services/code_preprocessors/PythonCodePreprocessorService.js, client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js
Fix #225 
Note: Seems that this is [line of code](https://github.com/google/tie/blob/master/client/services/code_preprocessors/PythonCodePreprocessorService.js#L152) will never be executed(which prevents 100% coverage of course).
There is nowhere to break the `while(true)` loop. I think it's safe to delete this line.
=> Fix #225: Add tests in client/services/code_preprocessors

client/components/LearnerViewDirective.js, client/domain/FeedbackObjectFactory.js, client/services/FeedbackGeneratorService.js, client/services/FeedbackGeneratorServiceSpec.js
As we discussed in [this thread](https://github.com/google/tie/issues/157), I talked with several people and finally decided to take your suggestions, which let users make less clicks. 
PTAL(Sorry about the messy diff view after resolving merge conflict.)
Screenshot:
Initial feedback:
Run the code with several syntax errors:
Click the link to display error details:
Fix the first error and run again(showing the second error detail without having to click the link):
Hide the error details:
Fix the error:
Navigating to other questions works well:
=> Fix #157: Give graduated feedback for syntax errors.

client/services/FeedbackGeneratorService.js, client/services/FeedbackGeneratorServiceSpec.js
Currently, when Karma tests are run, a console.error() message shows up midway along the following lines:
```
'Could not make the following object human-readable: ', function () { ... }
```
This PR fixes that. It used to be the case that we didn't convert all objects to JS, so that's why we had the console.error() before. But now that our conversion process is pretty comprehensive, I've turned the `console.error` into an actual `throw Error()` since we no longer expect it to happen in practice.
=> Fix error message that shows up when running Karma tests.

client/services/FeedbackGeneratorService.js
Credit to @eyurko for this suggestion.
=> When an invalid import is used, tell the user which libraries we currently support.

client/components/LearnerViewDirective.js
The aim of this PR is to reduce the height of the code font a bit, in order to make the feedback easier to read and use the space more efficiently. Would welcome feedback on the direction; I'm happy to withdraw this if it's not desired.
Existing UI:
New UI (introduced with this PR):
=> Make code font and padding a bit smaller in the feedback section.

client/domain/CodeEvalResultObjectFactory.js, client/services/FeedbackGeneratorService.js
This is a small change inspired by @a-zakem's note that both prerequisite checks and code eval results act on "code", but the former acts on raw code and the latter acts on preprocessed code. I'm making the name change so there's less confusion about what's what.
=> Rename getCode to getPreprocessedCode in the CodeEvalResult object.

client/components/LearnerViewDirective.js, client/components/LearnerViewDirectiveSpec.js
This was a bit harder to fix than I expected. The clearHistory() etc. functions on codeMirror did not seem to work, so I ended up just removing the editor from the DOM and replacing it with a new one after a short while.
=> Fix #244: clear the undo queue when the problem is switched.

client/components/LearnerViewDirective.js, client/domain/FeedbackObjectFactory.js, client/domain/SnapshotObjectFactory.js, client/services/FeedbackGeneratorService.js, client/services/ReinforcementGeneratorService.js, client/services/SolutionHandlerService.js, client/services/TranscriptService.js, client/services/code_preprocessors/CodePreprocessorDispatcherService.js, client/services/code_preprocessors/CodePreprocessorDispatcherServiceSpec.js, client/services/code_preprocessors/PythonCodePreprocessorService.js
We currently have a slightly weird pattern where we pass manually-constructed dicts with "feedback" and "reinforcement" keys to the frontend. This PR cleans this up by treating Reinforcement objects as a subpart of Feedback objects (especially since they're all now shown in the same pane in the UI anyway).
=> Make Reinforcement a sub-object of Feedback.

client/services/FeedbackGeneratorService.js
I introduced this bug in the #304 refactor, sorry. /cc @eyurko
=> Fix #309: Do not compute reinforcements when there is a runtime error.

client/components/LearnerViewDirective.js
Fix to Issue #368 
* Changed `html` min-height such that container divs will style the bottom navbar correctly even when window shrinks
=> Fix 368: Bottom Navbar Styling on Window Shrink

client/app.js, client/domain/PrereqCheckFailureObjectFactory.js, client/services/FeedbackGeneratorService.js, client/services/FeedbackGeneratorServiceSpec.js, client/services/code_evaluators/PythonPrereqCheckService.js, client/services/code_evaluators/PythonPrereqCheckServiceSpec.js
Fix to Issue #36 
* Added 2 PrereqCheckFailure types to account for invalid calls to the `System` and `AuxiliaryCode` classes
* Added new feedback for these new PrereqCheckFailure types in `FeedbackGenerator`
* Added relevant tests
=> Fix #36: Prevent Invalid System/AuxiliaryCode Calls

client/components/LearnerViewDirective.js
Fix to Issue #366 
* Changed styling in dark mode to make button controls not as bright
=> Fix #366: Change Button Control Styling in Dark Mode

assets/questions/findMostCommonCharacter.js, client/domain/ReinforcementObjectFactory.js, protractor_tests/question.spec.js, protractor_tests/questions.pageObject.js
Fix to Issue #370 
* Added helper function and adjusted test case input formatting to ensure spaces don't get collapsed when rendering reinforcement test case input
Example of old Reinforcement bullet rendering:
Example of Reinforcement with proposed changes:
=> Fix #370: Reinforcement Input Formatting

client/question/question.js
* Fixed bug where the ZeroDivisionError would get blocked by the Java Comment Regex for Wrong Language Syntax Detection
=> Fix Java Comment RegEx Bug

.eslintrc.json
* Added new `require-jsdoc` rule to linter so that we don't regress in adding JSDoc comments
*Note*: There's another related rule called [valid-jsdoc](http://eslint.org/docs/rules/valid-jsdoc) that enforces style and consistency within JSDoc comments. I wasn't sure whether we wanted to be that strict, and there are also a lot of ways we can specify it, which I'd love to get team input on if we do decide to go with adding this rule.
=> Add require-jsdoc to linter

assets/question_sets/strings.js, assets/questions/reverseWords.js, client/question/components/LearnerViewDirective.js, client/question/domain/FeedbackObjectFactory.js
This is a first pass at adding more feedback to the reverseWords question. There's yet more feedback that can be added, but I'm blocked by a lack of functionality, so I figured I'd submit this first, add the missing functionality, and then do another pass at adding more feedback.
I also found and fixed a couple of existing bugs (@theresa-lee PTAL):
- hintIndex was not being carried over when the code received "don't use print statements" feedback, so only the first message of a feedback set was ever being shown. This resulted in a frustrating UX since the later feedback was never reached.
- The loading dots were overlapping the reinforcements, which looked ugly. I gave them a top margin.
The additional functionality I plan to add in future PRs is the following:
- After giving a sequence …
=> First pass at improving reverseWords question.

client/question/question.js
Hi @rabidbit -- I took a quick look at this. Turns out what was happening was that the imports were being placed at class-level:
class StudentCode(object):
import X
import Y
def run():
and for some reason Skulpt wasn't finding them. On investigation, just importing everything that's supported at the top of the file seems to be the simplest way to handle this, so I went ahead and modified the starter code instead so that collections, math, etc. are automatically available.
The one thing I'm not sure about is whether we want to put a comment at the top of the coding area to say something like this:
```
```
but I'm not sure. On the one hand it gives info that might be useful. On the other hand I don't want to create the suggestion that the user should be using something from here, and it's …
=> Fix #412: just import everything at the outset.

client/question/services/code_preprocessors/PythonCodePreprocessorService.js, client/question/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js
I noticed this bug while running code in which the last line was a comment, e.g.:
```
def reverseWords(s):
return s
```
Because we now strip comments in order to avoid false-positive checks, additional trimming causes the number of lines to change. The app would therefore end up hanging, due to an error check in the CodeSubmission object that was meant to verify that the number of lines in the preprocessed code stayed the same. This PR fixes that by removing the trim().
=> Do not trim code while preprocessing, in order to preserve line numbers.

client/question/domain/FeedbackObjectFactory.js, client/question/domain/FeedbackObjectFactorySpec.js, client/question/question.html, client/question/question.js, client/question/questionSpec.js, client/question/services/FeedbackGeneratorService.js, client/question/services/FeedbackGeneratorServiceSpec.js, client/question/services/ReinforcementGeneratorServiceSpec.js, client/question/services/SolutionHandlerService.js, client/question/services/SolutionHandlerServiceSpec.js, client/question/services/TipsGeneratorService.js, client/question/services/TipsGeneratorServiceSpec.js, client/question/services/code_evaluators/PrereqCheckDispatcherService.js, client/question/services/code_evaluators/PythonPrereqCheckService.js, client/question/services/code_evaluators/PythonPrereqCheckServiceSpec.js
This is the first of a series of PRs dedicated to tips, i.e. non-blocking feedback that is shown above the regular feedback TIE provides.
This PR lays the groundwork for a tips framework, and converts the "you're using a print statement" warning into a system-generated tip. Subsequent PRs will add functionality for question-specific tips (previously known as "wrong-approach errors"), and introduce a graduated system for not showing tips after they have been ignored.
The PR also refactors the functionality for ignoring lines of code containing strings (cf. #413) into a common place, since that functionality is needed by both tips and prerequisite checks.
/cc @rabidbit
=> Introduce the concept of tips, i.e. non-blocking feedback.

client/question/domain/CodeEvalResultObjectFactory.js, client/question/domain/CodeEvalResultObjectFactorySpec.js, client/question/services/SolutionHandlerService.js, client/question/services/SolutionHandlerServiceSpec.js, client/question/services/TipsGeneratorService.js, client/question/services/TipsGeneratorServiceSpec.js
This PR adds task-specific tips (e.g. "you don't need regexes for this question") to the feedback flow. I still need to add tests for:
- CodeEvalResult.prototype.getIndexOfFirstFailedTask
- TipsGeneratorService.getTipParagraphs() to account for question-specific tips
and, in a future PR, make changes to show a given tip at most twice in succession (currently we show a tip whenever it applies).
In the meantime, though, @rabidbit -- could you PTAL at the code/UX? I'd like to confirm that the behavior and core ideas are correct. Thanks!
=> Add task-specific tips to the feedback flow.

client/question/components/LearnerViewDirective.js, client/question/components/LearnerViewDirectiveSpec.js, client/question/question.js
@eyurko PTAL -- this change preps the learner view directive to do other things besides autosaving on a code change event. This PR introduces no change in user behaviour; a subsequent PR will add functionality to show/hide unprompted feedback.
Also, /cc @rabidbit for info.
=> Refactor learner view to generalize the onCodeChange loop to do other things besides autosaving.

client/question/components/LearnerViewDirective.js
I've kept the styling to be roughly the same as a button (with padding) but it's a link instead, and it follows the style of the links that are shown in the feedback.
=> Changed the python primer button to a link (Fixes #456)

client/question/components/LearnerViewDirective.js
Using Sean's suggestion, resetting either the feedback or the code will clear the LocalStorage feedback. That means that if a user resets the code, the current feedback won't be cleared but if they refresh the page, then it won't be able to fetch any feedback, and will be blank. Resetting the feedback will remove the feedback both in the feedback window and in LocalStorage.
This should fix #479, #279, and #398.
=> Added Reset Feedback button and separating resetting code/feedback functionality

client/question/components/LearnerViewDirective.js
Following discussion in #467, the button is now disabled (but not visually) to the user when there is feedback pending. I can make CSS changes to the button but it looked like @rabidbit preferred to have it basically be disabled but not visibly so.
=> Disable button if there is feedback pending

client/question/components/LearnerViewDirective.js, client/question/components/SpeechBalloonsContainerDirective.js
Added final sentence to congratulatory feedback as suggested in [this comment](https://github.com/google/tie/issues/469#issuecomment-356783014).
Also fixed a regression caused by #492 that caused _all_ balloons to glow yellow when a new piece of code is submitted.
=> Add final sentence to congratulatory feedback. Fix regression caused by #492.

client/question/components/CodeSnippetDirective.js
=> Fix #477: Reduce line height for code snippets.

client/question/components/LearnerViewDirective.js
This addresses an accessibility bug where the dropdown menu seems to have three options (but it only has two).
I followed [this approach](https://webaim.org/techniques/forms/controls#select). However, note that this entails UI changes -- see bottom of screenshot below, in particular the added "Theme:" label. Please let me know what you think -- I'm happy to make any changes.
=> Remove dummy dropdown option from theme selector.

client/question/components/LearnerViewDirective.js
Button width appears to be too narrow for default Firefox settings on Linux.
=> Adjust button width for compatibility with Firefox

index.html
Since links are technically external to the page, they are not captured. This allows us to know whether users actually clicked the download link, whether they visited our page, whether they opened the license file, or whether they clicked the feedback form link.
=> Update Analytics to capture clicks

client/question/domain/PrereqCheckErrorObjectFactory.js, client/question/domain/PrereqCheckErrorObjectFactorySpec.js, client/question/domain/PrereqCheckFailureObjectFactory.js, client/question/question.html, client/question/services/code_evaluators/PythonPrereqCheckService.js, client/question/services/code_evaluators/PythonPrereqCheckServiceSpec.js
Expands the PrereqCheck to find the error line numbers, and pass it to the feedback object. To eventually highlight the line, and append to the feedback bubble.
This is PR 1 of 2, loop through the student code, find the error and pass it to the PrereqCheckFailureObjectFactory.
=> Add line numbers to PrereqCheck Obj, to display on feedback (#414)

client/question/services/CookieStorageService.js
We were confused why local instances of TIE weren't saving cookies, and now we know.
=> Update comments on cookie service.

client/question/components/CodeSnippetDirective.js
Note: This fixes a bug in the user submitted code speech balloons. It also fixed the issue observed in #556 ; however, if feedback speech balloon prints code snippets longer than 3 lines, it will be truncated as well. But I think that's fine because this places a limit on how much code text is placed in feedback speech balloons, and the point of the separate code windows is to offload lengthy code into a separate UI element.
=> Fix #556: Fix when "View full code" link is displayed

client/question/services/code_evaluators/PythonCodeRunnerService.js
* Add to comments regarding reasoning behind standardizing stdout array.
=> Fix #597: Explanation for extra characters after stdout.

client/question/services/ConversationManagerServiceSpec.js
This PR organizes the tests in ConversationManagerServiceSpec along the following lines:
- The order of the tests follows that in the new feedback flow.
- Each test description is limited to a single line, for readability.
- The code has been refactored to be largely outside the tests, so that the same student code can be reused in multiple tests.
- Variables that are the same for all tests have been made global so that they are not passed in every function call.
- A single question dict is used for all tests in this file.
- Stdout tests have been separated out into a separate test suite.
I am hoping that this will make it easier to add new tests and spot holes in coverage.
=> Organize the ConversationManagerServiceSpec tests according to the new feedback flow.

tests/e2e/utils.js
Adds expectAndAcceptAlert() to utils.js to simplify testing for the presence and text of alert dialogs.
=> adds a test utility function to test the presence of alert dialogs

client/question/components/LearnerViewDirective.js
When the selector is hidden, it affects other elements and creates jank by shifting windows a bit. Disabling the selector does not do this while still preventing the user from using the selector.
=> Disable theme selector instead of hiding it

client/question/components/LearnerViewDirective.js, tests/e2e/question.spec.js
This PR changes order of the feedback and coding windows in vertical/portrait mode. This is for a few reasons: (a) currently, the pop-up/modal covers the feedback window in horizontal layout and the coding window in vertical layout--this change lets it cover the feedback window in both modes with little to no changes to the pop-up/modal (b) users might not notice the feedback window if they do not scroll down enough--whereas with the proposed layout, it's fine because we can point the users to the coding window anyway and (c) the existing behavior is counter to normal wrapping behavior.
=> Un-reverse order in vertical layout
