assets/questions/i18n.json

I updated it according to comments on the previous branch.

Adding the RFC 4627-compliant version of the i18n json schema.

---

assets/questions/rle.json

Adding the RFC 4627-compliant version of the run-length encoding json schema.

---

client/services/code_preprocessors/CodePreprocessorDispatcherService.js
client/services/code_preprocessors/PythonCodePreprocessorService.js
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js

Write a simple preprocessor that wraps a submitted answer in a class.

---

assets/questions/i18n.json
client/app.html
client/app.js
client/components/LearnerViewDirective.js
client/domain/CodeEvalResultObjectFactory.js
client/domain/PromptObjectFactory.js
client/domain/QuestionObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/QuestionDataService.js
client/services/SolutionBrokerService.js
client/services/SolutionHandlerService.js
client/services/code_evaluators/PythonCodeRunnerService.js
client/services/code_preprocessors/CodePreprocessorDispatcherService.js
client/services/code_preprocessors/PythonCodePreprocessorService.js

This PR fleshes out the code submission pipeline. (When reviewing, you might want to try checking out this branch and running it locally.)
/cc @apicardgoog

Flesh out the pipeline for submitting and evaluating code.

---

client/app.html
client/components/LearnerViewDirective.js
client/domain/FeedbackObjectFactory.js
client/domain/QuestionObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/QuestionDataService.js
client/services/SolutionHandlerService.js
client/services/code_preprocessors/PythonCodePreprocessorService.js

Add support for multiple prompts within a single question.

---

assets/questions/i18n.js
assets/questions/parens.js
assets/questions/reverseWords.js
assets/questions/rle.js
client/components/LearnerViewDirective.js

Note: this also switches the left and right columns, otherwise the initial feedback doesn't make sense.
/cc @eyurko @apicardgoog

Add initial text to feedback frame; replace previous feedback when new feedback is obtained.

---

assets/questions/i18n.js
assets/questions/parens.js
assets/questions/reverseWords.js
assets/questions/rle.js
client/app.js
client/components/LearnerViewDirective.js
client/domain/CodeEvalResultObjectFactory.js
client/domain/PromptObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/SolutionHandlerService.js
client/services/code_evaluators/PythonCodeRunnerService.js
client/services/code_preprocessors/CodePreprocessorDispatcherService.js
client/services/code_preprocessors/PythonCodePreprocessorService.js
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js

Add support for targeted feedback for specific buggy functions.

---

assets/questions/reverseWords.js
client/components/LearnerViewDirective.js

Error running local tests on my Mac. Away from office; so, cannot test on my workstation. Creating pull request.

Revised UI with navigation and new next button.

---

.travis.yml
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js
scripts/run_karma_tests.sh

This replaces #18. Trying to trigger auto-presubmit checks by creating a new branch.
~~Not for review yet. Will send a ping once it's ready.~~
Edit: Now ready for review.

Run Karma presubmit checks automatically.

---

assets/questions/reverseWords.js

Reviewed and manually / autotested; LGTM.

Consolidate question by removing unnecessary instruction.

---

client/components/LearnerViewDirective.js

UI fixes: Add timestamp to feedback. Allow jumping between questions.

---

assets/questions/rle.js

Add auxiliary code for the run-length encoding problem.

---

assets/questions/rle.js

Sorry about that -- I thought I had already fixed the indentation.

Fix indentation and merge conflict.

---

client/services/code_preprocessors/PythonCodePreprocessorService.js
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js

I think I managed to split the PRs correctly. Tested.

Add support for helper functions in student code

---

client/app.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/code_evaluators/PythonCodeRunnerService.js

Tested manually and autotested.

Added support for 3 second timeout on code execution.

---

client/components/LearnerViewDirective.js

Not for merge. Needs code fix.

UI: Fix next button prompt and style. Add simple processing animation.

---

client/app.html
client/components/CodeSnippetDirective.js
client/components/LearnerViewDirective.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js

Fix #38: Show multiple space chars + tab chars correctly in feedback window.

---

client/app.html
client/domain/CodeEvalResultObjectFactory.js
client/domain/ErrorTracebackObjectFactory.js
client/domain/TracebackCoordinatesObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/SolutionHandlerService.js
client/services/code_evaluators/PythonCodeRunnerService.js

(This is done by introducing an ErrorTraceback domain object for the former.)

Clarify the difference between error traceback and error strings.

---

assets/tests/CodeCheckerService.js
assets/tests/QuestionSchemaValidationService.js
assets/tests/QuestionSchemaValidationServiceSpec.js
assets/tests/TaskSchemaValidationService.js
client/app.js
client/domain/QuestionObjectFactory.js
client/domain/StyleTestObjectFactory.js

@eyurko -- pretty sure I've missed some additional stuff you mentioned, but my thinking was, let's just get this in and then we'll have a baseline.

Add validation tests for questions.

---

assets/questions/reverseWords.js

Fixed default code for q1

---

assets/questions/rle.js

#89: Change the incorrect description for question-4.

Fix q4 description (#89)

---

assets/questions/i18n.js

Modified the original question description from 
" _returns an abbreviation of the string of the form `<first character><length of the middle of the string><last character>`._
to
" _returns an abbreviation of the string of the form `<first character><length of the middle of the string><last character>` if it shortens the input._ "

fix #88: i18n description confusion

---

client/components/LearnerViewDirective.js

Resolves Issue [108](https://github.com/google/tie/issues/108).

Fix #108: Removed the CSS which was conflicting with the line number gutter

---

assets/tests/QuestionSchemaValidationService.js
assets/tests/QuestionSchemaValidationServiceSpec.js
assets/tests/TaskSchemaValidationService.js
assets/tests/TaskSchemaValidationServiceSpec.js

Added three extra validation tests, two to check buggyOutputTests, and one to check uniqueness of titles.

---

client/components/CodeSnippetDirective.js

fix bug #84

---

client/services/SolutionHandlerService.js
client/services/code_preprocessors/CodePreprocessorDispatcherService.js
client/services/code_preprocessors/PythonCodePreprocessorService.js
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js

Resolve #148, replace previous one which has CLA issue

implement inputFunctionName feature for correctnessTest and buggyOutputTest

---

client/components/LearnerViewDirective.js

a) Removed the 'Question #:' prefix from question title
b) Changed the text color

Fix #189: Question Title UI Modifications

---

client/components/LearnerViewDirective.js
client/services/CodeStorageService.js
client/services/CodeStorageServiceSpec.js

This change contains both UI change (new button added) and backend change (code are removed from localStorage)

Fix #139: Add code reset button to page

---

client/components/LearnerViewDirective.js

With the new feature, the code will be auto-saved every minute.
This pull request contains UI change (Display/Hide 'Saving code now...')

Fix #208: Add code auto-save feature

---

assets/questions/parens.js

I literally just removed a tab, so reviewing shouldn't be too hard.

Fix #85: Question 2 hints now match user code

---

assets/tests/CodeCheckerService.js
assets/tests/TaskSchemaValidationService.js
assets/tests/TaskSchemaValidationServiceSpec.js

issue-158-verify-auxiliary-cotains-class-definition

---

client/domain/QuestionSetObjectFactorySpec.js

see issue #160 
code coverage result:

code for 100% coverage of QuestionSetObjectFactory

---

assets/questions/unknownAlphabet.js
assets/tests/QuestionSchemaValidationServiceSpec.js
assets/tests/TaskSchemaValidationServiceSpec.js

resolve previous [PL](https://github.com/google/tie/pull/179) of #120

create Unknown alphabet question

---

client/domain/ErrorTracebackObjectFactorySpec.js

Add test for ErrorTrackBack

---

assets/questions/strobogrammatic.js

Duplicate of (#141) for merge purpose.

Add Strobogrammatic problem.

---

client/services/QuestionDataServiceSpec.js

Issue 223 part2

---

client/app.js
client/components/LearnerViewDirective.js
client/components/LearnerViewDirectiveSpec.js
client/services/CodeStorageService.js
client/services/CodeStorageServiceSpec.js

This change includes both ui and backend change.
I also added some unit test for LearnerViewDirective (See LearnerViewDirectiveSpec)

Fix #213: Enable responsive autosave for user

---

client/domain/CodeSubmissionObjectFactory.js
client/services/code_preprocessors/PythonCodePreprocessorService.js

Now users can use the standard libraries implemented in Skulpt (https://github.com/skulpt/skulpt/tree/93d0dc6f19ba2008716787f737f2003cf6ea5bb9/src/lib, the js files).
A screenshot:

fixed the error when using stdlib in issue#100

---

assets/questions/bestMeetupLocation.js
assets/questions/bomberman.js
assets/questions/findChar.js
assets/questions/i18n.js
assets/questions/incNumber.js
assets/questions/mostCommonChar.js
assets/questions/palindrome.js
assets/questions/parens.js
assets/questions/reverseWords.js
assets/questions/rle.js
assets/questions/stringToWords.js
assets/questions/strobogrammatic.js
assets/questions/unknownAlphabet.js
assets/tests/TaskSchemaValidationService.js
assets/tests/TaskSchemaValidationServiceSpec.js
client/components/LearnerViewDirective.js

a) Updated the 'instructions' data schema for all the questions.
b) Updated the 'instructions' object validtions in TaskSchemaValidationService for asserting that each instruction is an associative array

Fix #215: Question window enhancements

---

client/domain/CodeEvalResultObjectFactorySpec.js
client/domain/CorrectnessTestObjectFactorySpec.js
client/domain/FeedbackObjectFactorySpec.js
client/domain/FeedbackParagraphObjectFactory.js
client/domain/QuestionObjectFactory.js
client/domain/QuestionObjectFactorySpec.js
client/domain/SnapshotObjectFactorySpec.js

CodeEvalResultObjectFactory, CorrectnessTestObjectFactory, FeedbackObjectFactory, SnapshotObjectFactory
see issue #222

Fix #222: 100% karma coverage for domain/

---

client/components/LearnerViewDirective.js

Fix #241: clear error message when it is not needed.

---

client/components/LearnerViewDirective.js

Background of code div didn't change in 'Dark' theme and code was unreadable.

added style to fix background color of instruction code in 'Dark' theme

---

assets/questions/runLengthEncoding.js
client/app.js
client/domain/TaskObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js

Made various run-length encoding improvements and added outputFunctionName to the results.

---

assets/question_sets/all.js
assets/question_sets/other.js
assets/questions/longestSubstring.js
assets/questions/sortItinerary.js
client/app.html

Should be able to close #122 and #123.

Merging longestSubstring and sortItinerary problems into TIE.

---

client/components/LearnerViewDirective.js

'Saving code...' text is now readable in Dark Mode. Temp fix for the background color height issue and also added Dark Night for code blocks in instructions.

Dark Theme Fixes: Fix #232, Temp Fix #234

---

assets/questions/isPalindrome.js
assets/tests/CodeCheckerService.js
assets/tests/TaskSchemaValidationService.js
assets/tests/TaskSchemaValidationServiceSpec.js

Fix issues with BuggyOutputFunction names.

---

client/services/code_preprocessors/PythonCodePreprocessorService.js
client/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js

Fixes #257 without all the garbage in #275.

Correctly add class names to student code.

---

client/domain/ErrorTracebackObjectFactory.js
client/services/code_evaluators/CodeRunnerDispatcherServiceSpec.js
karma.conf.js

Fixes the same problem as #276, but with a shinier, cleaner commit.

Clean commit of 276.

---

assets/questions/findMostCommonCharacter.js

(This is the first question in the default list. The test case that's shown at the outset, if you get it wrong, seems too complicated.)
Also added an extra test case for very short (1-character) strings, and tidied up the formatting a bit for consistency.
/cc @eyurko

Use a simpler test case for the first part of the findMostCommonCharacter question.

---

client/components/LearnerViewDirective.js
client/services/CodeStorageService.js

Hi @rabidbit, would you mind taking this for a spin? Thanks!

Fix #246: handle Safari error involving localStorage.

---

client/components/LearnerViewDirective.js

In order to direct attention to the most recent feedback, greying out the previous feedback.

Making previous feedback greyed out, but on hover regain full opacity.

---

hooks/pre-push

PhantomJS is causing some instabilities in Karma tests:
```
PhantomJS 2.1.1 (Linux 0.0.0) PythonCodePreprocessorService _jsonVariableToPython should correctly convert a JSON boolean array FAILED
Expected false to equal true.
client/services/SolutionHandlerServiceSpec.js:93:55
g@node_modules/es6-shim/es6-shim.min.js:11:1972
node_modules/es6-shim/es6-shim.min.js:11:1902
n@node_modules/es6-shim/es6-shim.min.js:11:2386
Expected 'def mockMainFunction():
return True' to equal 'Input: "task_1_correctness_test_2"
Output: False'.
client/services/SolutionHandlerServiceSpec.js:104:69
g@node_modules/es6-shim/es6-shim.min.js:11:1972
node_modules/es6-shim/es6-shim.min.js:11:1902
n@node_modules/es6-shim/es6-shim.min.js:11:2386
Expected 'def mockMainFunction():
return True' to equal 'Input: …
```

Use Chrome instead of PhantomJS for pre-push hook

---

client/services/SolutionHandlerServiceSpec.js
client/services/code_evaluators/CodeRunnerDispatcherServiceSpec.js

Asynchronous tests were not being run correctly before and were actually failing but these failures were not being recognized.
In order to test asynchronous functions, a done() callback is needed -- see https://jasmine.github.io/2.0/introduction.html#section-Asynchronous_Support. This PR adds it and fixes some bugs in the existing async tests.

Fix async tests; they were not running correctly before.

---

client/services/code_evaluators/PrereqCheckDispatcherServiceSpec.js
client/services/code_evaluators/PythonPrereqCheckServiceSpec.js

* Added tests for code coverage for the directory `client/services/code_evaluators`
* There is still one line that is not covered in `PythonCodeRunnerService.js`, but will try to see if it gets covered by expanding tests in other files.

Add Tests for client/services/code_evaluators folder

---

client/domain/TranscriptObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/ReinforcementGeneratorServiceSpec.js
client/services/SolutionHandlerServiceSpec.js

* Added tests for code coverage for all files in `client/services` folder except for `CodeStorageService`
* Made necessary change in `FeedbackGeneratorService.js` to make it run through paths properly
* Created `ReinforcementGeneratorServiceSpec.js`

Finish tests for services folder

---

client/app.js
client/domain/PrereqCheckFailureObjectFactory.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/SolutionHandlerServiceSpec.js
client/services/code_evaluators/PythonPrereqCheckService.js
client/services/code_evaluators/PythonPrereqCheckServiceSpec.js

* Resolves the issues brought up in Issue #323 
* Adds a Prereq error type for when there is code declared in the global scope
* Throws the necessary Prereq error when code is declared in the global scope
* Adds feedback for when there is an infinite recursive loop
* Added the associated tests

Fix issue #323

---

client/services/code_evaluators/CodeRunnerDispatcherServiceSpec.js

/cc @eledavi. This should fix the flaky tests.

Fix occasional failure of async tests.

---

client/components/LearnerViewDirective.js

Fix for Issue #333 
* Added explicit styling for select menus and buttons to make UI more consistent.
This is what the UI looks like right now:

Fix Issue 333 - Consistent Button Styling

---

client/components/LearnerViewDirective.js

Addresses #306 
* Added a privacy notice that we will not store code if the user is on the browser only version.
* Will appear on the bottom of the question window and below the feedback (if there are any). (**Note:** I wasn't sure where exactly to place it so I'm open to suggestions.)
* Will appear as: "**Privacy Notice:** Your code is only stored on your browser's local storage. In other words, we _do not_ store your code on any of our servers or databases." (**Note:** Am also open to suggestions for wording.)

Fix #306 Add Privacy Notice

---

client/domain/CodeSubmissionObjectFactory.js
client/services/code_preprocessors/PythonCodePreprocessorService.js

Deleting the function that removes the global imports.

Removing global imports from student code is not necessary

---

assets/questions/findMostCommonCharacter.js
assets/questions/internationalization.js
assets/questions/reverseWords.js

- mostCommonCharacter: drop unicode portion of question.
- reverseWords: detect case when entire string is reversed and provide specific feedback for that case.
- i18n: reword feedback message for "corner" case to sound less like a gotcha

Various content fixes.

---

assets/tests/CodeCheckerService.js
assets/tests/QuestionSchemaValidationService.js
assets/tests/TaskSchemaValidationService.js
client/app.js
client/components/CodeSnippetDirective.js
client/components/LearnerViewDirective.js
client/components/SyntaxErrorSnippetDirective.js
protractor_tests/questions.pageObject.js
protractor_tests/utils.js

* Added JSDoc Comments to all class files in the `assets/tests` folder
* Added JSDoc Comments to `app.js`
* Added JSDoc comments to `client/components` folder
* Added JSDoc Comments to all class files in `protractor_tests` folder

Add JSDoc Comments to Rest of Files

---

client/app.js
client/services/FeedbackGeneratorService.js
client/services/FeedbackGeneratorServiceSpec.js
client/services/SolutionHandlerServiceSpec.js

* Added series of user-friendly feedback responses to common run-time errors in `FeedbackGeneratorService`
* Added relevant tests for each runtime error response
* Changed affected test in `SolutionHandlerService`

Improve Run-time Error Feedback

---

.eslintrc.json
client/data/data.js
client/menu/menu.html
client/menu/menu.js
client/question/question.html
client/question/question.js

- Renamed data file to be consistent (all other files did not have the 'tie' in front)
- Created a menu.js file with a controller to grab the data from the other module services
- Moved shared constants

Added menu.js + controller to retrieve question data

---

client/question/services/code_preprocessors/PythonCodePreprocessorServiceSpec.js
hooks/pre-push

It's too easy to submit even if tests fail. I don't think we need this functionality, and this PR removes it altogether.

Prohibit pushing if checks fail.

---

client/question/components/LearnerViewDirective.js

Added Python Primer Button 

---

assets/questions/reverseWords.js

There's a bit more to come here, but I realized while working on this that I might have done the buggy-output-tests refactor incorrectly (it might be better to whitelist a set of test suites to run rather than blacklist a set of test suites not to run). Still thinking through this, but figured I might as well get all the other changes in first.

Add some more feedback to the 'reverse words' question.

---

client/question/services/FeedbackGeneratorService.js
client/question/services/SolutionHandlerServiceSpec.js

This fixes an error I introduced in an earlier PR (oops!) and adds a test to prevent it from happening again.

Fix error introduced in commit 200c144 when checking whether code has changed.

---

client/question/components/LearnerViewDirective.js
client/question/components/LearnerViewDirectiveSpec.js
client/question/components/MonospaceDisplayModalDirective.js
client/question/components/OutputSnippetDirective.js
client/question/components/SyntaxErrorSnippetDirective.js
client/question/question.html
client/question/services/MonospaceDisplayModalService.js
client/question/services/MonospaceDisplayModalServiceSpec.js
protractor_tests/question.spec.js

Hi @rabidbit -- PTAL and let me know if any changes are needed before this can be merged. For non-essential updates, I think it would be better to do those in a separate PR after getting the other basic stuff sorted out (e.g. stuff coming in from the top, styling of bubbles, etc.).
Thanks!

Show syntax errors and output printing requests in a modal. Have feedback come in from the top.

---

client/question/components/LearnerViewDirective.js

Thanks to @rabidbit for the CSS / HTML structure included in this PR.

Incremental change to show feedback using speech bubbles (no animation).

---

client/data/services/QuestionDataService.js
client/data/services/QuestionDataServiceSpec.js
client/question/components/LearnerViewDirective.js

The server specific backend file changes are in a CL.

When loading question, if server version, it will pull from datastore instead of local files.

---

client/question/components/LearnerViewDirective.js
client/question/components/SpeechBalloonDirectives.js
client/question/question.js

Fix speech balloon color transition (Issue #480 )

Fix speech balloon color transition (Issue #480)

---

client/question/components/LearnerViewDirective.js

Not sure what emoji to add but can do that in a separate PR! I just removed the button and overlay for now.

Fix for #482 - Removed Next button and overlay

---

client/question/domain/PrereqCheckFailureObjectFactory.js
client/question/question.js
client/question/services/FeedbackGeneratorService.js
client/question/services/FeedbackGeneratorServiceSpec.js
client/question/services/SolutionHandlerServiceSpec.js
client/question/services/code_evaluators/PythonPrereqCheckService.js
client/question/services/code_evaluators/PythonPrereqCheckServiceSpec.js

Yeah this almost included Sean's NOT FOR MERGE commit but I managed to clear it all out.
NOTHING TO WORRY ABOUT HERE.

Added StudentCode to forbidden namespaces.

---

client/docs/py-primer-dark.html
client/docs/py-primer-light.html

Made it more readable, added quick links, added more content.

Update Python Primer

---

client/question/components/LearnerViewDirective.js
client/question/components/LearnerViewDirectiveSpec.js

This is a blocking change; PTAL ASAP.

TaskCompleteEvent should fire even on question completion.

---

client/question/components/LearnerViewDirective.js

Remove incorrect parameters from EventHandlerService calls.

---

client/question/components/LearnerViewDirective.js

Looks like we just weren't saving the feedback after completing the problem!

Feedback is now stored after question completion

---

client/question/components/LearnerViewDirective.js

- Changed it to only change border color when hovering (to be consistent with the other buttons) and darker when active.
- Removed some unnecessary code.

Changed contrast of button color to comply with standards.

---

client/question/components/LearnerViewDirective.js

This PR implements a fix to help users not get stuck in the CodeMirror textarea when using the keyboard to navigate the TIE app. Now, tabbing will end up on the container of the CodeMirror area instead. Pressing Enter will enter the textarea, and pressing Escape will exit it and return to the usual tab ordering flow.
If you would like to experience this with a screenreader, you can do the following:
1. Install the ChromeVox chrome extension and enable it.
2. Open an instance of TIE and tab around, listening to what is coming in from ChromeVox. On tabbing to the code area, you should hear "Press Enter to access the code area" after it reads the text in it. On entering the code area, you should hear "Press Escape to exit the code area."

Fix accessibility bug where focus gets trapped in the CodeMirror area.

---

client/question/components/LearnerViewDirective.js

CodeMirror uses an inputStyle of "textarea" by default. This makes sense for sighted users since it enables visual highlighting etc. However it isn't great for accessibility. For example, upon deleting one word of a line, the screen reader announces the whole line as being deleted; and upon clicking enter to go to next line, the screen reader announces the previous line as being deleted.
This PR introduces an alternative editor that is triggered when the editor is tabbed into (which we will currently take as a proxy for keyboard-navigation usage). I tried modifying the codemirror options while the editor is running, but it turns out that that is not permitted, so the only option remaining seems to be to have two editors that reference the same data and to show the correct one depending on …

Use a more accessible input style for codemirror when it is tabbed into.

---

client/question/components/LearnerViewDirective.js

Change feedback link to Forms

---

client/question/components/LearnerViewDirective.js

Changing "I think I'm done" to "Get Feedback" to address observations and comments in user studies, where users are reluctant to click "I think I'm done", thinking they should have a complete solution first.
Adding title attributes to most of the buttons and links for context to the user.

Update button labels and titles

---

client/question/question.js
client/question/services/FeedbackGeneratorServiceSpec.js

Removed references to splicing.

---

client/docs/py-primer-dark.html
client/docs/py-primer-light.html

Also update format in dark mode and sync with light mode.

Update Python Primer doc with slicing and splicing sections

---

client/question/services/code_evaluators/PythonCodeRunnerService.js
client/question/services/code_evaluators/PythonCodeRunnerServiceSpec.js

whoooops~
Like I said, we should really get a flow chart.

Allow server to catch user syntax errors before runtime.

---

client/question/components/LearnerViewDirective.js

Add CSS classes for privacy modal reject button. Very fancy.

---

client/question/components/LearnerViewDirective.js
client/question/domain/FeedbackObjectFactory.js
client/question/services/FeedbackGeneratorService.js
client/question/services/FeedbackGeneratorServiceSpec.js
client/question/services/SolutionHandlerServiceSpec.js
client/question/services/code_evaluators/PythonPrereqCheckService.js

Added Error Line Number to FeedbackParagraph, feedback generator adds: '(See line N of the code.)' when errorLineNumber is added feedback.appendTYPEParagraph().

Bug #414 Pt. 2 - Adding errorLineNumber to feedbackParagraph, and highlighting the line

---

client/question/components/PrivacyModalDirective.js
client/question/question.js

Change reject URL to be client version's homepage.

---

client/config/deploymentSpecificConfig.js
client/question/components/PrivacyModalDirective.js
client/question/components/TextWithMarkdownLinksSnippetDirective.js
client/question/components/TextWithMarkdownLinksSnippetDirectiveSpec.js
client/question/question.js
client/question/services/FeedbackGeneratorServiceSpec.js
client/question/services/ThemeNameService.js
client/question/services/ThemeNameServiceSpec.js

sorry for the extra commit -- shouldn't be there.

 Add PRIMER_DIRECTORY_URL to client.

---

client/question/components/SpeechBalloonsContainerDirective.js
client/question/domain/SpeechBalloonObjectFactory.js
client/question/domain/SpeechBalloonObjectFactorySpec.js

* Add new function to check if right code balloon is present.
* Base loading dots off of right code balloon's presence.

Fix #558: Loading dots appear right after submission.

---

client/question/components/LearnerViewDirective.js
client/question/services/SessionHistoryService.js
client/question/services/SessionHistoryServiceSpec.js

* Students can no longer spam "Get Feedback" button.

Disable "Get Feedback" button when code submission is processing.

---

client/question/components/SpeechBalloonsContainerDirective.js

Moving question.html up a level in path invalidated the path to cake.

Fix cake path

---

client/question/components/CodeSnippetDirective.js

This is a follow-up to #591, specifically [this comment](https://github.com/google/tie/pull/591#pullrequestreview-129026731).

Refactor code snippet directive to have clearer variable names.

---

assets/questions/reverseWords.js
client/config/deploymentSpecificConfig.js
client/data/domain/TipObjectFactory.js
client/data/domain/TipObjectFactorySpec.js
client/question.html
client/question/components/LearnerViewDirective.js
client/question/question.js
client/question/services/PrintTerminalService.js
client/question/services/PrintTerminalServiceSpec.js
client/question/services/UnpromptedFeedbackManagerService.js
client/question/services/UnpromptedFeedbackManagerServiceSpec.js

Add print terminal to page depending on if printing is supported.

---

client/question/services/code_evaluators/PythonCodeRunnerService.js
client/question/services/code_evaluators/PythonCodeRunnerServiceSpec.js

stderr will come from the server empty in these cases, so we need to make sure that the codeevalresult takes that into consideration.

Handle empty stderr.

---

client/question/components/LearnerViewDirective.js
client/question/domain/SpeechBalloonObjectFactory.js
client/question/domain/SpeechBalloonObjectFactorySpec.js
client/question/services/SessionHistoryService.js
client/question/services/SessionHistoryServiceSpec.js

Reference for when TIE is iframed. When the page is first loaded, the balloon flashes yellow like a normal feedback balloon, then fades to the default white:

Remove question and add intro message if iframed.

---

client/question/components/LearnerViewDirective.js
client/question/domain/SpeechBalloonObjectFactory.js
client/question/question.js
client/question/services/SessionHistoryService.js
client/question/services/SessionHistoryServiceSpec.js

When "Submit for Grading" is clicked, the code balloon first shows up. Then after a second of loading dots, the confirmation message appears. The end result is shown below:

Show confirmation that code was submitted.

---

assets/base.css
client/question/components/LearnerViewDirective.js

TIE with maximum width:
TIE with minimum width before collapsing:
TIE with collapsed windows:
I'll have this up on our trial site soon so that you can actually interact with the page.

Add responsive feedback window.

---

client/question/services/ConversationManagerServiceSpec.js
client/question/services/ConversationManagerServiceTestUtils.js
client/question/services/FeedbackGeneratorService.js
client/question/services/FeedbackGeneratorServiceSpec.js

This is in preparation for a future PR that bulks these tests up in order to ensure that the various workflows are correct.

Simplify conversation manager service tests.

---

assets/questions/pirateTranslator.js
client/menu.html
client/question.html

I ended up creating a completely new client for this...

Initial check in of pirate question.

---

client/question/components/LearnerViewDirective.js
tests/e2e/protractor.conf.js
tests/e2e/question.pageObject.js
tests/e2e/question.spec.js
tests/e2e/utils.js

- Adds more E2E tests for the Question Page:
- reset feedback
- switching theme
- links display
- responsive UI
- Replaces checkForConsoleError in utils.js by expectNoConsoleLogs: All log levels should be captured by the tests and no console output should be expected.
- Adds more utility functions for responsive UI testing

Adds more e2e tests for the Question page

---

assets/questions/findMostCommonCharacter.js

One issue I ran into testing this: it would be great for the performance tests to allow for custom messages because "try making this linear" is not super-helpful for a beginner who hasn't learned O yet. I'd like to say something like: "It looks like your code is slow for large inputs. Are you going over the string multiple times? Using a dictionary might allow you to solve this problem with a single pass over the string." Or something like that.

Add two more buggy output tests to findMostCommonCharacter question.

---

assets/questions/findMostCommonRepeatedCharacter.js
client/menu.html
client/question.html

Sorry for the discontinuity here but this is a clean PR without all the other changes.
I've addressed the only remaining issue from your last comments which was to allow 'aaa' to be counted as 1 or 2 repeated characters.

New PR for repeated character question

---

client/question/services/EventHandlerService.js
client/question/services/EventHandlerServiceSpec.js

#643 but without the CLA issues.

CodeResetEvents should submit the event batch to the backend.

---

assets/questions/findMostCommonCharacter.js

Based on content edits from Beth.

Update most common character question.

---

client/config/deploymentSpecificConfig.js
client/data/services/QuestionDataService.js
client/data/services/QuestionDataServiceSpec.js
client/question/components/LearnerViewDirective.js
client/question/question.js
client/question/services/CurrentQuestionService.js
client/question/services/CurrentQuestionServiceSpec.js
tests/e2e/utils.js

Should be fine to merge, but any servers using this would have to implement the server-side support alongside the merge otherwise they'll crash.

Add support for server-side 404 page.

---

assets/questions/bomberman.js
assets/questions/checkBalancedParentheses.js
assets/questions/findAlphabet.js
assets/questions/findBestMeetupLocation.js
assets/questions/findClosestValueBst.js
assets/questions/findFirstNonRepeatingCharacter.js
assets/questions/findMostCommonCharacter.js
assets/questions/findMostCommonRepeatedCharacter.js
assets/questions/getStrobogrammaticNumbers.js
assets/questions/incrementDecimalCodedNumber.js
assets/questions/internationalization.js
assets/questions/isLeapYear.js
assets/questions/isPalindrome.js
assets/questions/longestSubstring.js
assets/questions/pirateTranslator.js
assets/questions/reverseWords.js
assets/questions/runLengthEncoding.js
assets/questions/sortItinerary.js
assets/questions/splitStringIntoWords.js
assets/tests/TaskSchemaValidationService.js
assets/tests/TaskSchemaValidationServiceSpec.js
client/data/domain/TaskObjectFactory.js
client/data/domain/TaskObjectFactorySpec.js
client/question/domain/CodeEvalResultObjectFactorySpec.js
client/question/services/ConversationManagerServiceSpec.js
client/question/services/UnpromptedFeedbackManagerServiceSpec.js
client/question/services/code_evaluators/PythonCodeRunnerServiceSpec.js

This reverts commit e51996e32dbb01461e24758cd045e52c48648146, which introduced hints to the task schema. (Per team discussion, we might need to revisit the design of this feature a bit.)

Revert "Add hints field to task schema. (#662)"

---

client/question/components/LearnerViewDirective.js
client/question/components/MonospaceDisplayModalDirective.js
client/question/question.js

Currently the width of the modal is not responsive when user adjusts the width of their browser window.

Make modal width response

---

tests/e2e/question.pageObject.js
tests/e2e/question.spec.js
tests/e2e/utils.js

- question.pageObject.js:
- Fixes bug that prevented correct simulation of multi-line code submission in setCode()
- Forces protractor to wait for TIE to be ready before and after simulating a code submission in runCode()
- question.spec.js:
- Replaces beforeEach block by beforeAll to avoid reloading and resetting code before every test case (this also led to inconsistent analytics session state)
- Fixes formatting

Updates e2e test suites and utilities
